First steps with Theano.

In [1]:
%load_ext version_information
%version_information theano, numpy

Software versions
Python 2.7.6 64bit [GCC 4.8.2]
IPython 4.0.1
OS Linux 4.1.13 boot2docker x86_64 with Ubuntu 14.04 trusty
theano 0.7.0.dev-30cc6380863b08a3a90ecbe083ddfb629a56161d
numpy 1.8.2
Tue Dec 08 01:56:19 2015 UTC

## [NumPy Refresher](http://deeplearning.net/software/theano/tutorial/numpy.html#broadcasting)

In [2]:
import numpy as np

Matrix rows are examples/observations. Matrix columns are features/dimensions of the example.

In [3]:
my_matrix = np.asarray([[1., 2], [3, 4], [5, 6]])
my_matrix

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

This is a 3 row, 2 column matrix.

In [4]:
my_matrix.shape

(3, 2)

Access elements as you would in an `R` matrix, _except that counting starts at 0_.

In [5]:
my_matrix[2, 0]

5.0

NumPy does something called _[broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)_ where it makes a smaller array compatible with a larger array. 

Two examples are shown below, along with images from [a visual guide](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) to broadcasting.

In [6]:
np.array([1.0, 2.0, 3.0]) * 2

array([ 2.,  4.,  6.])

![](https://scipy.github.io/old-wiki/pages/image0013830.gif)

In the example above, the scalar `2.0` is stretched into a 3-element array. This example is just like `c(1, 2, 3) * 2` in `R`. (I don't know yet how more sophisticated examples of broadcasting compare with `R` behaviors.)

In [7]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([0.0, 1.0, 2.0])
a + b

array([[  0.,   1.,   2.],
       [ 10.,  11.,  12.],
       [ 20.,  21.,  22.],
       [ 30.,  31.,  32.]])

![](https://scipy.github.io/old-wiki/pages/image0020619.gif)

## [Baby Steps - Algebra](http://deeplearning.net/software/theano/tutorial/adding.html)

### Adding Two Scalars

Create a function in Theano to add two numbers together

In [8]:
import theano.tensor as T
from theano import function

In [9]:
x = T.dscalar("x")
y = T.dscalar("y")
z = x + y
f = function([x, y], z)

Symbols are typed. `T.dscalar` is a 0-dimensional array (_scalar_) of doubles. Theano types are not the same as classes. 

In [10]:
# the class of x
type(x)

theano.tensor.var.TensorVariable

In [11]:
# the theano type of x
x.type

TensorType(float64, scalar)

In [12]:
z

Elemwise{add,no_inplace}.0

In [13]:
# Use pp to pretty print the computation associated to z
from theano import pp
pp(z)

'(x + y)'

We perform the computation in `z` by wrapping in that `function` or using its `eval` method.

In [14]:
f(2, 3)

array(5.0)

In [15]:
f(16.3, 12.1)

array(28.4)

In [16]:
z.eval({x: 2, y: 3})

array(5.0)

### Adding two matrices

Create a function to add two matrices

In [17]:
x = T.dmatrix("x")
y = T.dmatrix("y")
z = x + y
f = function([x, y], z)

Theano can work 2D arrays or `numpy` arrays.

In [18]:
f([[1, 2], [3, 4]], [[10, 20], [30, 40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

In [19]:
array1 = np.array(range(1, 5)).reshape([2, 2])
array2 = np.array(range(10, 50, 10)).reshape([2, 2])
f(array1, array2)

array([[ 11.,  22.],
       [ 33.,  44.]])

### Exercise

Modify this boilerplate code to compute `a ** 2 + b ** 2 + 2 * a * b`.

```python
import theano
a = theano.tensor.vector()      # declare variable
out = a + a ** 10               # build symbolic expression
f = theano.function([a], out)   # compile function
```

In [20]:
a = T.vector()
b = T.vector()
z = a ** 2 + b ** 2 + 2 * a * b
f = function([a, b], z)
f(range(0, 5), range(5, 10))

array([  25.,   49.,   81.,  121.,  169.])

This matches the R code solution

```r
a <- 0:4
b <- 5:9
a ^ 2 + b ^ 2 + 2 * a * b
#> [1]  25  49  81 121 169
```