First steps with Theano.

In [12]:
%load_ext version_information
%version_information theano, numpy

The version_information extension is already loaded. To reload it, use:
  %reload_ext version_information


Software versions
Python 2.7.6 64bit [GCC 4.8.2]
IPython 4.0.1
OS Linux 4.1.13 boot2docker x86_64 with Ubuntu 14.04 trusty
theano 0.7.0.dev-30cc6380863b08a3a90ecbe083ddfb629a56161d
numpy 1.8.2
Thu Dec 03 02:46:01 2015 UTC

### [NumPy Refresher](http://deeplearning.net/software/theano/tutorial/numpy.html#broadcasting)

In [13]:
import numpy as np

Matrix rows are examples/observations. Matrix columns are features/dimensions of the example.

In [14]:
my_matrix = np.asarray([[1., 2], [3, 4], [5, 6]])
my_matrix

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

This is a 3 row, 2 column matrix.

In [15]:
my_matrix.shape

(3, 2)

Access elements as you would in an `R` matrix, _except that counting starts at 0_.

In [16]:
my_matrix[2, 0]

5.0

NumPy does something called _[broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)_ where it makes a smaller array compatible with a larger array. 

Two examples are shown below, along with images from [a visual guide](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) to broadcasting.

In [17]:
np.array([1.0, 2.0, 3.0]) * 2

array([ 2.,  4.,  6.])

![](https://scipy.github.io/old-wiki/pages/image0013830.gif)

In the example above, the scalar `2.0` is stretched into a 3-element array. This example is just like `c(1, 2, 3) * 2` in `R`. (I don't know yet how more sophisticated examples of broadcasting compare with `R` behaviors.)

In [18]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[  1.,   2.,   3.],
       [ 11.,  12.,  13.],
       [ 21.,  22.,  23.],
       [ 31.,  32.,  33.]])

![](https://scipy.github.io/old-wiki/pages/image0020619.gif)